#!/usr/bin/env node
/**
 * Prepares the local/CI environment for Playwright E2E tests.
 * - Waits for infra
 * - Configures Keycloak
 * - Runs DB migrations + E2E seed data
 * - Writes .env.e2e.generated for app servers
 */
import { spawnSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '../..');

const isCI = process.env.CI === 'true';
const composeArgs = isCI
    ? ['-f', 'docker-compose.yml']
    : ['-f', 'docker-compose.yml', '-f', 'docker-compose.e2e.yml'];

const DB_PORT = process.env.E2E_DB_PORT || (isCI ? '5432' : '5433');
const KEYCLOAK_URL = process.env.KEYCLOAK_URL || (isCI ? 'http://localhost:8080' : 'http://localhost:9081');
const DB_NAME = process.env.DB_NAME || 'cleantrack';
const DB_USER = process.env.DB_USER || 'postgres';
const DB_PASSWORD = process.env.DB_PASSWORD || 'postgres';
const REDIS_PORT = process.env.E2E_REDIS_PORT || (isCI ? '6379' : '6380');
const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET || 'e2e-test-secret-min-32-chars-long!!';

function run(cmd, args, opts = {}) {
    console.log(`\n▶ ${cmd} ${args.join(' ')}`);
    const result = spawnSync(cmd, args, { stdio: 'inherit', cwd: opts.cwd || root, env: { ...process.env, ...opts.env }, shell: process.platform === 'win32' });
    if (result.status !== 0) {
        process.exit(result.status ?? 1);
    }
}

function runCapture(cmd, args, opts = {}) {
    const result = spawnSync(cmd, args, {
        cwd: opts.cwd || root,
        env: { ...process.env, ...opts.env },
        encoding: 'utf-8',
        shell: process.platform === 'win32',
    });
    if (result.status !== 0) {
        console.error(result.stderr || result.stdout);
        process.exit(result.status ?? 1);
    }
    return (result.stdout || '').trim();
}

// 1. Wait for infrastructure
run('node', ['scripts/e2e/wait-for-url.mjs', `${KEYCLOAK_URL}/realms/master`, '180000']);

// 2. Keycloak realm, client, test users
run('npx', ['ts-node', 'scripts/setup-keycloak.ts'], {
    env: {
        KEYCLOAK_URL,
        KEYCLOAK_REALM: 'cleantrack',
        KEYCLOAK_CLIENT_ID: 'cleantrack-client',
    },
});

// 3. Client secret for NextAuth / backend
const clientSecret = runCapture('node', ['scripts/e2e/get-keycloak-secret.mjs'], {
    env: { KEYCLOAK_URL, KEYCLOAK_REALM: 'cleantrack', KEYCLOAK_CLIENT_ID: 'cleantrack-client' },
});

const backendEnv = `# Auto-generated by scripts/e2e/bootstrap.mjs — do not commit
DB_HOST=localhost
DB_PORT=${DB_PORT}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
PORT=3000
REDIS_HOST=localhost
REDIS_PORT=${REDIS_PORT}
KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_URL}
KEYCLOAK_URL=${KEYCLOAK_URL}
KEYCLOAK_REALM=cleantrack
KEYCLOAK_CLIENT_ID=cleantrack-client
KEYCLOAK_CLIENT_SECRET=${clientSecret}
KEYCLOAK_ADMIN=${process.env.KEYCLOAK_ADMIN || 'admin'}
KEYCLOAK_ADMIN_PASSWORD=${process.env.KEYCLOAK_ADMIN_PASSWORD || 'admin'}
`;

const frontendEnv = `# Auto-generated by scripts/e2e/bootstrap.mjs — do not commit
PORT=3001
NEXT_PUBLIC_API_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3001
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
KEYCLOAK_CLIENT_ID=cleantrack-client
KEYCLOAK_CLIENT_SECRET=${clientSecret}
KEYCLOAK_ISSUER=${KEYCLOAK_URL}/realms/cleantrack
`;

const e2eEnv = `# Auto-generated by scripts/e2e/bootstrap.mjs — do not commit
BASE_URL=http://localhost:3001
E2E_ADMIN_USERNAME=admin_tenant
E2E_ADMIN_PASSWORD=password123
E2E_ADMIN_SITE_USERNAME=admin_site
E2E_ADMIN_SITE_PASSWORD=password123
E2E_USER_SITE_USERNAME=user_site
E2E_USER_SITE_PASSWORD=password123
`;

mkdirSync(join(root, 'tests/.auth'), { recursive: true });
writeFileSync(join(root, 'backend/.env.e2e.generated'), backendEnv);
writeFileSync(join(root, 'frontend/.env.e2e.generated'), frontendEnv);
writeFileSync(join(root, '.env.e2e.generated'), e2eEnv);

console.log('\n✅ Wrote backend/.env.e2e.generated, frontend/.env.e2e.generated, .env.e2e.generated');

// 4. Database migrations + seed (deps must be installed before this step)
run('npm', ['run', 'migration:run'], {
    cwd: join(root, 'backend'),
    env: { DB_HOST: 'localhost', DB_PORT, DB_USERNAME: DB_USER, DB_PASSWORD, DB_NAME },
});
run('npx', ['ts-node', 'scripts/seed-e2e-data.ts'], {
    cwd: join(root, 'backend'),
    env: { DB_HOST: 'localhost', DB_PORT, DB_USERNAME: DB_USER, DB_PASSWORD, DB_NAME },
});

console.log('\n✅ E2E bootstrap complete');
